# Generated by Django 4.2.8 on 2024-02-22 11:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=200)),
                ('numero_rue', models.CharField(max_length=10)),
                ('code_postal', models.CharField(max_length=10)),
                ('commune', models.CharField(max_length=100)),
                ('type_logement', models.CharField(choices=[('APP', 'Appartement'), ('MAI', 'Maison'), ('BUR', 'Bureau')], max_length=3)),
                ('etage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('entreprise', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=200)),
                ('numero_rue', models.CharField(max_length=14)),
                ('post_zip', models.CharField(max_length=20)),
                ('TVA', models.CharField(max_length=14)),
                ('phonenumber', models.CharField(max_length=100)),
                ('national', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('date_dispo_debut', models.DateField()),
                ('date_dispo_fin', models.DateField()),
                ('abonnement', models.IntegerField(default=0)),
                ('total_devis', models.IntegerField(default=0)),
                ('limits_reached', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mon_dem.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='mon_dem.customuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='mon_dem.movingcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mon_dem.movingcompany')),
            ],
        ),
        migrations.CreateModel(
            name='MovingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dispo_debut', models.DateField()),
                ('date_dispo_fin', models.DateField()),
                ('volume_estime', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recommendation', models.TextField(blank=True)),
                ('national', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('total_send', models.IntegerField(default=0)),
                ('limits_reached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('adresse_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_arrivee', to='mon_dem.adresse')),
                ('adresse_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_depart', to='mon_dem.adresse')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_dem.customuser')),
                ('service', models.ManyToManyField(to='mon_dem.services')),
            ],
        ),
        migrations.AddField(
            model_name='movingcompany',
            name='devis',
            field=models.ManyToManyField(to='mon_dem.movingrequest'),
        ),
        migrations.AddField(
            model_name='movingcompany',
            name='pays',
            field=models.ManyToManyField(to='mon_dem.pays'),
        ),
        migrations.AddField(
            model_name='movingcompany',
            name='region',
            field=models.ManyToManyField(to='mon_dem.region'),
        ),
        migrations.AddField(
            model_name='movingcompany',
            name='service',
            field=models.ManyToManyField(to='mon_dem.services'),
        ),
        migrations.AddField(
            model_name='movingcompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('platform_name', models.CharField(max_length=100)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mon_dem.presentation')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mon_dem.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('justification', models.ManyToManyField(to='mon_dem.justification')),
                ('moving_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='mon_dem.movingcompany')),
                ('moving_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='mon_dem.movingrequest')),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mon_dem.pays'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mon_dem.region'),
        ),
    ]
