# Generated by Django 4.2.8 on 2024-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_dem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movingcompany',
            name='devis',
            field=models.ManyToManyField(blank=True, to='mon_dem.movingrequest'),
        ),
    ]
