# Generated by Django 4.2.8 on 2024-02-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mon_dem', '0002_alter_movingcompany_devis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movingcompany',
            name='calendar',
        ),
        migrations.AddField(
            model_name='calendar',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mon_dem.movingcompany'),
            preserve_default=False,
        ),
    ]
