# Generated by Django 4.2.8 on 2024-02-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mon_dem', '0003_remove_movingcompany_calendar_calendar_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.RemoveField(
            model_name='movingcompany',
            name='date_dispo_debut',
        ),
        migrations.RemoveField(
            model_name='movingcompany',
            name='date_dispo_fin',
        ),
        migrations.CreateModel(
            name='Dispo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='mon_dem.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='dispo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mon_dem.dispo'),
        ),
    ]
